### ISSUE TITLE
What is the difference between these branch.

### ISSUE THREAD

**Issue by xianlubird** [crosbymichael/dockerui#131]
I clone the master branch and then run ./dockerui .But when I use chrome to view 127.0.0.1:9000,there is nothing in the page.All white.  I find the wiki write that ./dockerui -a dist,but I can not find dist folder in master branch. I checkout dist branch and run ./dockerui -a dist, it works.I want to know that, why the master branch can run in docker container with command ./dockerui but I can not run it on my local host?

**Comment by kevana** [comment]
Release tags are created from the dist branch and the Docker Hub images are built using these tags. You are able to run directly from this branch because the compilation output is committed to the repo in the dist branch. In the master branch none of the compilation output is committed (keeps commit diffs cleaner). In order to run from the master branch you need to compile the binary and javascript, directions are [here](https://github.com/crosbymichael/dockerui/wiki/Developing-DockerUI). Does this clear things up?

**Comment by xianlubird** [comment]
Yeah! Very clear. Thank you very much.
