### ISSUE TITLE
Add a 'pull' button to get a updates

### ISSUE THREAD

**Issue by zedtux** [crosbymichael/dockerui#70]
As far as I can tell there no such a button to executer a `docker pull` of a given image. It would be nice to have one.

**Comment by kevana** [comment]
I've been running into a lot of issues with this because the stream from docker pull contains multiple top-level objects (e.g. `{...}{...}{...}`) and I haven't found a library that handles this. OboeJS [only works with a single top-level object](https://github.com/jimhigson/oboe.js/issues/44), anyone know of another streaming JSON library that might work?

**Comment by kevana** [comment]
Implemented in #125.
